/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import React from 'react';
import { PlayIcon } from './icons';

// Placeholder data for the gallery
const galleryVideos = [
  { id: 1, title: 'Epic Roast of a Toaster', thumbnail: 'https://placehold.co/400x225/1e293b/fb923c?text=RoastyPit' },
  { id: 2, title: 'Squirrel vs. Skyscraper', thumbnail: 'https://placehold.co/400x225/1e293b/f97316?text=RoastyPit' },
  { id: 3, title: 'A Cat\'s Dramatic Monologue', thumbnail: 'https://placehold.co/400x225/1e293b/ea580c?text=RoastyPit' },
  { id: 4, title: 'The Secret Life of Garden Gnomes', thumbnail: 'https://placehold.co/400x225/1e293b/d97706?text=RoastyPit' },
  { id: 5, title: 'Why Mondays are Overrated', thumbnail: 'https://placehold.co/400x225/1e293b/b45309?text=RoastyPit' },
  { id: 6, title: 'An Ode to Procrastination', thumbnail: 'https://placehold.co/400x225/1e293b/92400e?text=RoastyPit' },
];

const GalleryPage: React.FC = () => {
  return (
    <main className="w-full max-w-5xl mx-auto flex-grow p-8">
        <div className="bg-slate-800 border border-slate-700 rounded-2xl shadow-xl w-full flex flex-col">
            <header className="p-6 border-b border-slate-700 shrink-0 text-center">
                <h2 className="text-2xl font-bold text-white">Viral Video Gallery</h2>
            </header>
            <div className="p-8">
                <p className="text-slate-400 mb-8 text-center">A curated collection of the best videos generated by the RoastyPit community. Get inspired for your next roast!</p>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                    {galleryVideos.map((video) => (
                    <div key={video.id} className="group relative overflow-hidden rounded-lg shadow-lg border border-slate-700/50 cursor-pointer">
                        <img src={video.thumbnail} alt={video.title} className="w-full h-full object-cover" />
                        <div className="absolute inset-0 bg-black/60 flex flex-col justify-end p-4 opacity-0 group-hover:opacity-100 transition-opacity">
                        <h3 className="text-white font-semibold">{video.title}</h3>
                        </div>
                        <div className="absolute inset-0 flex items-center justify-center">
                        <div className="w-16 h-16 bg-black/50 rounded-full flex items-center justify-center opacity-0 group-hover:opacity-100 scale-75 group-hover:scale-100 transition-all duration-300">
                            <PlayIcon className="w-8 h-8 text-white" />
                        </div>
                        </div>
                    </div>
                    ))}
                </div>
            </div>
        </div>
    </main>
  );
};

export default GalleryPage;